### ISSUE TITLE
Basket Variables Limit und große Label Table

### ISSUE THREAD

**Issue by hansendx** [ddionrails/steering#11]

**Comment by kwenzig** [comment]
**Basket Variables Limit:**

Es bedarf noch der Recherche:

- Wie groß kann ein basket technisch derzeit werden, ohne ein timeout zu verursachen.
- Wieviele Variablen sind in den bereits gespeicherten Baskets?

Ad hoc-Lösung: verhindern, dass zu viele Variablen in den Basket gelegt werden können.

**große Label Table**

Die Label Table bei Variablen mit mehr als 100 Wertelabeln (ISCO, KldB) kann unterdrückt werden.

**Comment by kwenzig** [comment]
Timeouts der Server haben abgenommen.

**Comment by hansendx** [comment]
Es ist schwer abzuschätzen wie das für die Baskets Limit sein sollte.
Wenn mehrer Nutzer aufwendige anfragen stellen oder der Server zu heiß läuft sinkt das limit. Wenn sonst keiner etwas vom server will, dann klappen auch noch aufwendige anfragen.
Um die 1000 Variablen merkt man auf jeden Fall schon, dass es anstrengend wird.

**Comment by hansendx** [comment]
Die Einschränkung der LabelTable Größe ist implementiert: 
https://github.com/ddionrails/ddionrails/pull/1052

Die Einschränkung des Basket wird komplizierter, weil die Implementation des Basket an sich so komplex ist.

**Comment by hansendx** [comment]
Resolved by ddionrails/ddionrails/pull/1062
