### ISSUE TITLE
Longgrafiken

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#15]
https://git.soep.de/soep-generierungen/soeplong/issues/200#note_9896

**Comment by jgoebel** [comment]
Jan redet mit Andreas über die Lieferung der URLs.

**Comment by kwenzig** [comment]
Es gibt ein vorbereitenden Treffen am 17.02.

**Comment by kwenzig** [comment]
@isieber erarbeitet eine Tabelle mit syear und p/h-Zuordnung. Knut wird die in die Metadaten einpflegen.
