### ISSUE TITLE
Skizze für Überarbeitung des Templates für Darstellung einer Variable anfertigen

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#17]
- soll auch beinhalten: Lange description für Variable anzeigen
- dabei auch überlegen, ob Metadatenstandard für Variablen spezifiziert werden kann #9

**Comment by kwenzig** [comment]
https://docs.google.com/drawings/d/1bbGFhtr-6B9dLzQLaUhf_k7eYUPbYlQ-zc0kDAj9Uhs/edit?usp=sharing

**Comment by hansendx** [comment]
Ich mache anhand des Textes mal eine Prototyp Seite.

**Comment by kwenzig** [comment]
Ergebnisse 1. Review:

- Im Titel soll die Information Datensatz und Variablenname zusammengefasst werden, entweder durch eine Dachzeile mit Datensatzname oder durch datensatz/variable
- Tooltipps, die die Icons erklären sollen ausgeweitet werden auf Identifikatoren bzw. Labels, die folgen (falls das möglich ist und nicht mit Links kollidiert)
- im Infokasten soll das englische und deutsche Variablenlabel angezeigt werden (die Tabelle Variable Label and Value Labels  wird entsprechend umbenannt, dort wird das variablen label entfernt)
- Fragen sollen vorerst nur auf englisch angezeigt werden
- Label Table umbenennen nach "Codes of related variables with the same concept"
- tooltip "related variables": variables with the same concept. Auch die anderen Registerkarten könnten gut einer Erläuterung gebrauchen.
- Sortierung der Values in Grafik, Value Table und Label Table sollten eigentlich der gleichen Logik gehorchen. Als optimal wird eine Sotierung erst nach den Werten >=/<0 (valid/missing values), und innerhalb dieser Abschnitte betragsmäßig aufsteigend empfunden. Wie aufwändig das für die Grafik ist, ist zu prüfen. Für die Label Table könnte das den Server zusätzlich beanspruchen. (Entscheidung nach Prüfung für Grafik)
- Grafik: Es fehlt noch eine Grafik für metrische Variablen, in der Statistik-Box werden entsprechende Werte für Variablen, deren gültige Werte nicht gelabelt sind ausgegeben. Thema ist auch noch Long-grafiken.

**Comment by hansendx** [comment]
Changes are performed here https://github.com/ddionrails/ddionrails/pull/1268

**Comment by hansendx** [comment]
"Codes of related variables with the same concept" seems a bit redundant.
Are there variables with the same concept that are not related?
Users might not even know what a concept is in this context.

**Comment by kwenzig** [comment]
"Codes of related variables (with the same concept)" Motivation: I want to inform the user, what "related" means.

**Comment by kwenzig** [comment]
There are variables with m any different values, e.g. https://paneldata.org/soep-core/data/pgen/pgkldb2010. This results in a huge diagram and a huge table "Value Labels". For variables with more than ~30 values these two elements could be initially collapsed and somehow unfolded on request.

**Comment by kwenzig** [comment]
The tab "Input variables" has URL https://ddionrails.soep.de/soep-core/data/pgen/pgtatzeit#origin_variables, tab "Output variables" has url https://ddionrails.soep.de/soep-core/data/pgen/pgtatzeit#target_variables.
The term origin should be changed to input, and target to output. It would be nice, if the links would become functional and open the respective tab.

**Comment by kwenzig** [comment]
- es fehlt noch das feature für die vielen Fragebögen (Bootstrap Modal)

**Comment by kwenzig** [comment]
Regarding the different tables (related/input/output):
- URLs would be nice, c.p. https://github.com/ddionrails/steering/issues/17#issuecomment-658156541
- a merged table as default, that combines the content of the 3 tables, could help to get a more complete overview over the network from the perspective of the variable (and answer the question, which of the three tables is the most appropriate default).

**Comment by kwenzig** [comment]
Merged table no priority.
