### ISSUE TITLE
Übersicht über Instrumente

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#19]
Wollen wir Metadaten in questionnaires und attachments so ergänzen, dass Tabellen wie diese
![grafik](https://user-images.githubusercontent.com/6614820/76540318-471f9680-6482-11ea-8cb8-7e9304c714a7.png)
[https://paneldata.org/soep-core](https://paneldata.org/soep-core)
automatisch erzeugt werden?

**Comment by urahm** [comment]
Hi, 
Wir machen grade ziemlich ähnliches für die Doku auf den FDZ-SOEP-Seiten: 
https://www.diw.de/sixcms/detail.php?id=diw_01.c.738704.de
Wir basteln noch an der genauen Sortierung/Selektion, aber die Metadaten nutzen wir auf jeden Fall auch (und müssten sie entsprechend ergänzen)

**Comment by kwenzig** [comment]
Wollen wir das mit den Publikationen verknüpfen?

**Comment by kwenzig** [comment]
Die Arbeit an https://ddionrails.soep.de/iab-soep-mig/ in https://github.com/ddionrails/steering/issues/53 hat gezeigt, dass die Übersicht über Instrumente (und Lücken der Dokumentation) verbessert werden muss. Ziel wäre eine Tabelle aus https://github.com/paneldata/soep-core/blob/master/metadata/instruments.csvbzw. der Quelle https://git.soep.de/soep-generierungen/Dokumentation/-/blob/master/meta/questionnaires.csv zu bauen, die eine Standardsortierung (Jahr, Typ) an und neu sortiert bzw. auch eingeschränkt werden kann. Diese Tabelle sollte ein Ersatz für https://ddionrails.soep.de/soep-core/#instruments sein.
Herausforderung: Es nicht zu studienspezifisch werden lassen.

**Comment by kwenzig** [comment]
Diskussionsvorschlag: https://docs.google.com/drawings/d/1NBdbxLml36YBGv7euhbhq1YMazhc7zD43Ify_A559e8/edit?usp=sharing

**Comment by kwenzig** [comment]
Das wäre mal so eine "neue" instruments.csv
[instruments.update.csv](https://github.com/ddionrails/steering/files/8115392/instruments.update.csv)
