### ISSUE TITLE
Bilder für Variablen und Fragen

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#2]

**Comment by hansendx** [comment]
@kwenzig:
> - @hansendx spricht mit Andreas über Wege, die Long-Grafiken zu importieren.
> - Weiterhin sind bereits CATI-Screenshots vorhanden, die entsprechen aufbereitet werden können.

**Comment by hansendx** [comment]
@kwenzig will die Bilderproduktion für Fragen anstoßen.
