### ISSUE TITLE
Studienspezifische Suche

### ISSUE THREAD

**Issue by hansendx** [ddionrails/steering#20]
Am GIP wird die Studienspezifische Suche vermisst.
Ein komplettes Suchinterface in die Studienseite zu pressen, wie es vorher war, würde ich nicht machen aber ich könnte mir zwei dinge vorstellen, die die Nutzer unterstützen könnten.

1. Eine Verlinkung auf der Studienseite, die direkt die Facette der Studie in der Suche setzt: [Search GIP](https://paneldata.org/search/all?Study=%5B%22German%20Internet%20Panel%20%28GIP%29%22%5D)
2. Ein Eingabeschlitz (kein direkter suchschlitz), der bei Eingabe zur suche weiterleitet: [(Life Satisfaction) [Search]](https://paneldata.org/search/all?Study=%5B%22SOEP-Core%22%5D&Search=%22Life+Satisfaction%22)

**Comment by jgoebel** [comment]
Variante 1 verstehe ich und finde ich auch gut. Aber bei Variante 2 bringt mich der Link zu einer quasi leeren Suche? Soll das so sein?

**Comment by hansendx** [comment]
Lösung 1 wird Bevorzugt. Die zusätzlichen Kosten um Lösung 2 zu implementieren entsprechen momentan nicht dem zusätzlichen nutzen.

**Comment by hansendx** [comment]
https://github.com/ddionrails/ddionrails/pull/1241
