### ISSUE TITLE
veraltete Variablen werden beim Import nicht gelöscht

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#23]
In https://git.soep.de/soep-generierungen/soeplong/-/issues/297 zeigt sich, dass Variablen, die z.B. nicht mehr in der neuen Version enthalten sind,  nicht gelöscht werden. Beispiel: https://paneldata.org/soep-core/data/hl/hlc0049 (war nicht in Stata-Dateien und nicht in den übermittelten Metadaten).
Eine Option wäre, den Datenebstand erst zu löschen bevor das Update erfolgt.
Nebeneffekte:

- Variablen im Basket
- Persistenz von Links

**Comment by kwenzig** [comment]
Der Import wird weiter bearbeitet.

**Comment by hansendx** [comment]
Adressed with https://github.com/ddionrails/ddionrails/commit/6065a95de54debd1a48723f6ac7c875c8627d03e
