### ISSUE TITLE
SOEPTransfer Projekt

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#24]
Idee: Innerhalb von paneldata.org gibt es gewichtete 2-3 dimensionale Tabellen, die interaktiv durch die Nutzer:innen zusammengestellt werden können.
Wahrscheinlicher Start Anfang 2021 nach der Auswertung des Barcamps, versprochener Milestone Prototyp August 2021.

Die angebotenen features werden wohl stark davon abhängen, wo welche Daten zur Verfügung stehen:

- Interaktion mit den Daten: alle Möglichkeiten
- Interaktion mit einem vereinfachten Datensatz (der ohnehin erstellt werden soll): sehr wenige Datenschutzbedenken
- Aufruf von vorberechneten Tabellen, vgl. (vermutlich) https://covid19pulse.usc.edu/

Die Projektleitung (Start ab Mitte des Jahres) sollte ca. nach ihrem ersten Monat zum paneldata.org-Treffen eingeladen werden. (Ggfs. ständig)

**Comment by jgoebel** [comment]
Gespräch mit Katja und Überarbeitung des Gesprächs-Leitfadens. Nach ersten Gesprächen Besprechung wegen paneldata geplant.

**Comment by kwenzig** [comment]
Erste Tabellen-Entwürfe werden zugänglich gemacht.
