### ISSUE TITLE
Import nach Änderungen benötigt zu viel manuelle Nacharbeit

### ISSUE THREAD

**Issue by hansendx** [ddionrails/steering#27]
1. Es gibt keinen standardisierten Prozess für die Vorbereitung der Daten.
2. Die vorhandene "automatische" Vorverarbeitung der Daten ist veraltet und mittlerweile nicht mehr funktionsfähig. 

Related: #3 #8 #9

**Comment by kwenzig** [comment]
@hansendx will analyse the current situation and make suggestions how to streamline the process.

**Comment by hansendx** [comment]
Data processing code pieces were refactored and collected in the [paneldata_pipeline](https://github.com/ddionrails/paneldata_pipeline/) python package.
The package provides a command line interface entry point.
The old scripts needed manual changes to the code to control the program flow whereas the new entry point takes several arguments for this instead.
[Twinlife](https://github.com/paneldata/twinlife) was the first study to be processed with the package.
[soep-core](https://github.com/paneldata/soep-core) metadata still contains old structures and needs refactoring to work with the package.

**Comment by hansendx** [comment]
TODO:
-----

- [x] Update soep-core metadata structure.
- [x] Implement data compliance tests as GitHub ci action.
- [x] Implement data processing pipeline as GitHub ci action.

**Comment by hansendx** [comment]
TODO?:
------

- [x] Test relations in data compliance tests

Relational test will take a lot of time.
Goodtables might not be optimized enough for this.
It could be necessary to implement this functionality instead.

**Comment by hansendx** [comment]
> ## TODO?:
> 
>     * [x]  Test relations in data compliance tests
> 
> 
> Relational test will take a lot of time.
> Goodtables might not be optimized enough for this.
> It could be necessary to implement this functionality instead.

Relation control functionality was implemented as part of the paneldata_pipeline package: https://github.com/ddionrails/paneldata_pipeline
