### ISSUE TITLE
PDF für Fragebogen generieren/Metadaten checken

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#28]
PDF für einen Fragebogen soll erzeugt werden, möglichst automatisch nach einem push, bei dem seine Metadaten geändert werden.
Vorher könnte man die Validität der Metadaten des einen Fragebogen testen und prüfen, ob die Metadaten überhaupt valide sind. Für alles liegen R/LaTeX-Skripte vor.

**Comment by kwenzig** [comment]
mit so einem Aufruf müsste das Skript zurechtkommen:
# C:\Users\kwenzig>C:\R-Project-for-Windows\R-3.5.1\bin\Rscript.exe D:\lokal\QuestCSV2LaTeX\R\CSV2LaTeX.r --scriptmode 1 --questionnaire soep-core-2018-e2 --scriptrepo D:/lokal/QuestCSV2LaTeX/ --metarepo D:/lokal/core-doku/

Knut gibt Bescheid, wenn das Skript soweit läuft.

**Comment by kwenzig** [comment]
Aktueller Stand:
- Es gibt ein Testskript, das Rückmeldungen zu gepushten Fragebogen-Metadaten geben kann.
- PDF-Skript wurde ergänzt, dass es per Skript ausgeführt werden kann und einzelne  Modi per Tabelle spezifiziert werden können. Jeder einzelne Modus soll dann nacheinander gestartet werden.

**Comment by hansendx** [comment]
Dann fehlt eigentlich nur noch

- [x] Spezifikation der Modi
- [x] Implementation der Modi
- [x] Nutzung der Modi in der Pipeline

Oder?

**Comment by kwenzig** [comment]
Wäre es sinnvoll bei https://git.soep.de/soep-generierungen/Dokumentation/-/pipelines/new den Modus (scriptmode) als Variable auswählen zu können? Dann würden nicht alle PDFs erzeugt werden müssen, wenn was spezifisches gebraucht wird. Default für die automatische Pipeline wäre dann erster Modus.

**Comment by hansendx** [comment]
Ich habe die GitLab pipeline mal angepasst.
Theoretisch müsste sie jetzt das manuelle setzen vom scriptmode erlauben, wenn das R Skript die Modi implementiert hat.
