### ISSUE TITLE
Domain ddionrails.org

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#30]
- Domain gehört uns nicht
- Zeit für Rebranding (kaum DDI, kein Ruby)?

**Comment by hansendx** [comment]
Der name stört mich auch schon eine Weile.
Eine Umbenennung würde etwas an Arbeit mit sich bringen.
Es hat auf jeden Fall nichts mehr mit Ruby on Rails zu tun.

**Comment by kwenzig** [comment]
Ist kein operatives Problem mehr. Stata-Ados können über http://ddionrails.github.io/soeptools/ installiert werden. Umbenennung würde mehr Arbeit kosten als Nutzen stiften.
