### ISSUE TITLE
Anpassung Skriptgenerator an v34/v35

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#4]
Der Skriptgenerator muss noch auf v34 und bald auch auf v35 geupdatet werden.

Spätestens, wenn die long-Files integriert werden sollen, ist die Gelegenheit da, ihn wartungsfreundlicher zu gestalten. Es besteht wohl Modernisierungsbedarf an der Codebasis.

Eine Option wäre, dass er nur noch long-Files prozessiert, aber für Variablen aus den raw-Files entsprechende long-Variablen zugeordnet werden. (Dafür könnte man sowohl Informationen aus dem concept als auch generations verwenden.)

Eine volle Parametrisierung, entweder auf Ebene des Generators oder auf Ebene der Statistiksoftware, wäre zu prüfen.

**Comment by kwenzig** [comment]
- Ingo schaut bis zu nächsten Sitzung wegen v35, um einen Beschlussvorschlag zu machen.
- #13 ist auf jeden Fall anzugehen.

**Comment by kwenzig** [comment]
Ingo wird Änderung für v35 auf Testsystem vorschlagen.

**Comment by hansendx** [comment]
@isieber und @mpahl wollen sich das zusammen anschauen.

**Comment by kwenzig** [comment]
Marius und Ingo sind fast im Plan. Melden sich, wenn es etwas zu testen/begutachten gibt.

**Comment by kwenzig** [comment]
https://github.com/ddionrails/ddionrails/issues/1150
https://github.com/ddionrails/ddionrails/issues/1151
https://github.com/ddionrails/ddionrails/issues/1152
https://github.com/ddionrails/ddionrails/issues/1153

**Comment by hansendx** [comment]
Addressed by https://github.com/ddionrails/ddionrails/commit/f13a09fc30baea90091295412c8f0eac8249d960
