### ISSUE TITLE
Persistente Links zu Variablen und Fragen

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#6]
Anwendungsfälle:

- PDF-Dokumentation
- SOEPhelp
- Fragebogenentwicklung

In der Datenbank gibt es bereits eindeutige IDs für Objekte.

Zu unterscheiden ist auch, ob die Form der Links konstant bleiben soll oder ob der Link an sich persistent sein soll.

1. Aktuell ist die Form der URL einer Variable `https://paneldata.org/<study>/data/<dataset>/<variable>`
2. Wenn Links an sich persistent sein sollen, ist auch eine Lösung erforderlich, wenn eine Variable in einer neuen Version nicht mehr vorhanden ist.

**Comment by kwenzig** [comment]
- Für die Verlinkung sollen die URLS mit Namen der Objekte verwendet werden.
- Diese Links zeigen dann auf die letzte Version des Objekts (etwa: Studie/Datensatz/Variable oder Studie/Fragebogen/Frage). Wenn das Objekt nicht mehr vorhanden ist, gibt es Fehler 404.
- Vor der breiten Verwendung (etwa in PDFs oder SOEPhelp) will @hansendx die Syntax noch verbessern (ästhetische Änderungen).
- Es gibt Use-Cases für die Objekte Datensatz, Fragebogen, Variable, Frage, dafür müsste @hansendx Vorschläge für die Linksyntax (Sprache sollte im Link enthalten sein) machen.
- Im SOEPcompanion werden tatsächlich schon URLs zu paneldata.org verwendet: http://companion.soep.de/Topics%20of%20SOEPcore/index.html#demography-and-population
- Alternative war die interne stabile UUID, @hansendx hat allerding die URLs mit Objektnamen empfohlen.

@jgoebel: Ist damit der Use Case Fragebogenentwicklung abgedeckt?

**Comment by jgoebel** [comment]
Wenn mit Frage eine "jahresspezifische Frage in einem bestimmten Fragebogen" gemeint ist, dann wäre das aus meiner Sicht abgedeckt.

**Comment by kwenzig** [comment]
Konstruktionsprinzipen für Links zu Fragen, Variablen, Concepts und Topics:
```

* Datensatz: https://paneldata.org/<study>/datasets/<dataset> (keine Version?!)
* Variable: https://paneldata.org/<study>/datasets/<dataset>/<variable> (keine Version?!)
* Fragebogen/Instrument: https://paneldata.org/<study>/instruments/<questionnaire>
* Frage: https://paneldata.org/<study>/instruments/<questionnaire>/<question>
* Concept: https://paneldata.org/concept/<concept> (Studienunabhängig?, Kollisionen!)
* Topics: https://paneldata.org/<study>/topics/<en|de>?open=topic_<hc

```
Themen also:
* Sprachen
* Versionen

---
update 2022-12-13: Datensatz, Variable, Fragebogen und Frage aktualisiert
