### ISSUE TITLE
Label table überarbeiten

### ISSUE THREAD

**Issue by hansendx** [ddionrails/steering#72]
Der `Label Table` der unter Variablenansichten angezeigt wird ist noch größtenteils unverändert.
Er wird in Django, also auf dem Server, erzeugt und ist dadurch und generell eher ineffizient.
Dazu kommt, dass er sich so schlecht in die Sprachwechsel-Funktion der Seite integrieren lässt.

Beim refactoring wäre es gut generell über die Darstellung dieser Information nachzudenken und vielleicht neue features
mit hinzuzufügen.

**Comment by kwenzig** [comment]
Die Label Table ist eigentlich nur sinnvoll, wenn es in der Studie mindestens zwei Variablen mit dem gleichen (nicht leeren) concept gibt. Sonst sollte sie ausgeblendet werden. (Ich sehe gerade, es gibt einen globalen Schalter in der study.md. Der erfüllt einen ähnlichen Zweck. - Funktioniert aber nicht.)

**Comment by hansendx** [comment]
Ja, da steht etwas in der study.md. Das wird aber nirgendwo benutzt. Kann also raus.
Ich habe mir den code fuer den label table nochmal angeschaut und festgestellt, dass er probleme mit concepts hat, wo nur variablen ohne values oder nur mit missings sind. Habe das repariert und filtere jetzt auch dannach, dass mindestens zwei variablen drin sind. Eine studienübergreifende Flag ist also nicht mehr nötig.
